[package]
name = "finalfrontier"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[dependencies]
cfg-if = "0.1"
fnv = "1"
ndarray = "0.11"
ndarray-rand = "0.7"
rand = "0.4"

[dev-dependencies]
lazy_static = "1"
maplit = "1"

[features]
avx-accel = []