[package]
name = "finalfrontier"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]

[dependencies]
byteorder = "1"
cfg-if = "0.1"
failure = "0.1"
fnv = "1"
hogwild = { path = "../hogwild" }
ndarray = "0.11"
ndarray-rand = "0.7"
ordered-float = "0.5"
rand = "0.4"
zipf = "3.0.*"

[dev-dependencies]
lazy_static = "1"
maplit = "1"
