[package]
name = "finalfrontier-utils"
version = "0.2.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
description = "Train and use word embeddings with subword representations"
documentation = "https://git.danieldk.eu/finalfrontier/about"
homepage = "https://github.com/danieldk/finalfrontier"
repository = "https://github.com/danieldk/finalfrontier.git"
license = "Apache-2.0"

[dependencies]
clap = "2"
failure = "0.1"
finalfrontier = { path = "../finalfrontier", version = "0.2.0" }
indicatif = "0.9"
memmap = "0.6"
num_cpus = "1"
rand = "0.4"
stdinout = "0.4"
