[package]
name = "hogwild"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
description = "Data types for hogwild SGD"
documentation = "https://docs.rs/hogwild/"
homepage = "https://git.danieldk.eu/finalfrontier/about"
repository = "https://git.danieldk.eu/finalfrontier"
license = "Apache-2.0"

[dependencies]
ndarray = "0.11"
